### ISSUE TITLE
save svg

### ISSUE THREAD

**Issue by xandyxor** [rawlins/svgling#3]
hi 
how to save svg file?

**Comment by rawlins** [comment]
There are a few options:

**From within Jupyter**: if you use shift+right click on the image, this should bring up the regular browser context menu (for firefox and chrome at least), where you can select "Save image as..."

**Programmatically**: If you're used to saving figures in e.g. R, this might be the most natural even in Jupyter. You can use the SVG (`svgwrite`) interface itself to save files programmatically. Here is a small example of how to do this:

```
t = svgling.draw_tree("S", "NP", "VP")
t.movement_arrow((1,), (0,), stroke_width=1)
t.get_svg().saveas("test.svg") # get an svgwrite.Drawing object and save it
```

Since SVG is just text, you could also use the svgwrite to get at the text and copy and paste it, with e.g. `t.get_svg().tostring()`.

Also, if you're using things at the command line, the `svgwrite` module if run directly supports writing basic tree svg to stdout, see the Makefile for an example of how to do that.

Thanks for the question, I'll make a note to add something about this to the documentation next time I do a pass.

**Comment by xandyxor** [comment]
Wow ! I get it !!!!!
Thank you for your project and answer.
